### ISSUE TITLE
feat: Show end for some of the global events

### ISSUE THREAD

**Issue by lcottercertinia** [certinia/debug-log-analyzer#115]
### Is your feature request related to a problem?

Skipped log entries is show from when skipped appears all the way to the end, despite the fact that the log continues after the skipped section.

### Describe the solution you'd like

- I would like the skipped event (and for any others where it is possible) to have an end time so we only see it covering the section of the timeline that it occurred for and not to the end.
- It would also be nice if non fatal events were shown in a shade of yellow instead of green following a traffic light system of severity.

**Comment by lukecotter** [comment]
I looked into this a bit and have some thoughts.
How do we want to show this? Currently the timeline highlight starts where the event occurred and ends at the next or the end time.

![image](https://user-images.githubusercontent.com/4013877/159889167-8f7809d7-e6bc-44fe-b8d3-e2f46617e726.png)

We could change it to have an end time for where event ends e.g the log skipping ended and methods carried on
![image](https://user-images.githubusercontent.com/4013877/159889504-0c24069f-549e-4fcf-9968-e5f689d5aead.png)

However sometimes the amount of skip can be very small and the bar would not be visible.
I was wonder if we display the green area as larger than it is in those cases and shrink it as we zoom?
@kjonesffdc What do you think? are there alternatives? or is the current approach better?
