### ISSUE TITLE
feat: replace sfdx exec with @salesforce/apex-node

### ISSUE THREAD

**Issue by lcottercertinia** [certinia/debug-log-analyzer#122]
### Is your feature request related to a problem?

We currently use SFDX via exec to get logs from an org. 
This could cause problems with different versions of SFDX, it would be safer to have a fixed version of @salesforce/apex-node and not to use exec.

### Describe the solution you'd like

Replace sfdx exec call with [@salesforce/apex-node](https://www.npmjs.com/package/@salesforce/apex-node) [github](https://github.com/forcedotcom/salesforcedx-apex)
      
Example usage in [sfdx-vscode](https://github.com/forcedotcom/salesforcedx-vscode/blob/01ff453253121d1334d862681d583f56c60dcbd9/packages/salesforcedx-vscode-apex/src/commands/forceApexLogGet.ts)

https://github.com/nawforce/apex-link-gulp/blob/main/src/gulp.ts

**Other indfo**
https://github.com/forcedotcom/salesforcedx-apex/blob/main/src/logs/logService.t

https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/src/commands/forceApexLogGet.ts

https://github.com/forcedotcom/sfdx-core/blob/main/src/org/connection.ts

https://github.com/jsforce/jsforce/issues/934

**Comment by lcotterffdc** [comment]
Due to the way that messages are imported in sfdx-core it can not currently be bundled 
Look for `Messages.importMessagesDirectory(pathJoin(__dirname));` in [ConfigFile.js](https://github.com/forcedotcom/sfdx-core/blob/107070d43cfc223c7b4fb9bfa6c1ec1c10166b97/src/config/configFile.ts)

Seems this has already be reported forcedotcom/sfdx-core#298

**Comment by lcotterffdc** [comment]
Still can not bundle [apex-node](https://github.com/forcedotcom/salesforcedx-apex) or [sfdx-core](https://github.com/forcedotcom/sfdx-core) until these two issues are resolved

https://github.com/jsforce/jsforce/pull/1343
https://github.com/forcedotcom/node-bunyan/pull/14

https://github.com/jsforce/jsforce/issues/1342
