### ISSUE TITLE
Add ability to export 'Analysis' to CSV 

### ISSUE THREAD

**Issue by Feldstrom** [certinia/debug-log-analyzer#25]
### Is your feature request related to a problem?
Currently if you copy and paste the information from the Analysis tab it requires you to manually format the columns. There is no space or delineation between columns that you can use to separate them. 

### Describe the solution you'd like
The ability to export or copy a formatted Analysis log to a spreadsheet/CSV.

### Describe alternatives you've considered
Copy & paste is a work around but it requires tremendous manual work to format the data into a usable form. 

### Additional context
Columns after being copy/pasted to spreadsheet:
![image](https://user-images.githubusercontent.com/30249667/119023991-7455b780-b957-11eb-8c45-ffa2504c8076.png)

**Comment by nawforce** [comment]
Sorry for the delay on responding to this. I think that would be really nice to have, would make sharing/saving the data quite a lot is easier. 

We have been working on trying to make the codebase a bit easier for other developers to work on. Once is done we should be able to start working on some new features.

**Comment by lcottercertinia** [comment]
@Feldstrom 
It has taken longer than we wanted to get to this, but we wanted to refactor the grid before taking this on.
We now have a PR in proposal that adds features to address this + should be included in the v1.7 release
Let us know if this solves things for you or if you have feedback we can include.
There are screenshots on the pr that show the output as copied to a google sheet or the exported file opened in excel.

Here are the 2 features we added:
- Copy data to clipboard directly from Analysis grid by focusing on the grid and using `ctrl + c` or `cmd + c`
- Export to CSV file using the `Export to CSV` action in the grid header menu
