### ISSUE TITLE
feat: Database old view.

### ISSUE THREAD

**Issue by mihailTr-19** [certinia/debug-log-analyzer#279]
At first, great thank you for your ext, it's really awersome.

Could you please add possibility to swith to the old view for the Database tab. For me it was more usefull when I can see full query, can copy it or some parts of it, and I see the spot where it was used without some actions.

**Comment by lcotterffdc** [comment]
Hi @mihailTr-19 

Thanks for providing feedback it really does help us improve things and I am glad you like the extension.

Firstly I just wanted to get across that the reason for the refactor was to more easily add advanced features in new versions such as grouping by a range of files including the SObject name and a range of filtering such as time ranges etc as well as a tonne of useful new features that just were not possible with the old implementation.

We do not really want to be supporting the old and new view and I would prefer to address feedback by improving the new view. 

I think you have some really good points here. Being able to see the whole query and paste parts of it is definitely something that is useful and I will look at making easier. In a future version we want to introduce a better way of viewing really long SOQL queries #253 where the super long field lists would other wise get in the way, check it out and give us your views so we can make that a really nice feature.

From what I understand the work here is to 
- Make the full query visible + able to copy and paste the whole thing or a sub section of it?

Could you explain a bit more what you mean when you said
> and I see the spot where it was used without some actions
Do you just mean that you copy the query then search in your project where it is used? or something else?
I am trying to work out if there is a missing feature or improvement that can be made in the analyser.

**Comment by lcotterffdc** [comment]
Thanks again for clearing this up, it really helps me improve things. 

I would prefer not to add a setting to control how much is shown, I think I prefer a click to expand / show behaviour. 
We can look at doing something like that. In the mean time I have change it (in a branch) to show the full query. 
I have some snags with copy + past to work out. 

**Callstack**
You can [see the callstack](https://github.com/certinia/debug-log-analyzer#database) by clicking on one of the soql rows once the group is expanded. it also show soql analysis on the right.
Maybe it is not clear this detail panel exists?
https://raw.githubusercontent.com/certinia/debug-log-analyzer/main/lana/dist/v1.6/db-lana.png

At the moment it will only show one of these details panels at a time but I could easily change it. 

**Number of SOQL**
As you say we do order the soql groups by number of soql query and we also show the number in red at the end of the group.
<img width="1118" alt="Screenshot 2023-06-03 at 09 18 11" src="https://github.com/certinia/debug-log-analyzer/assets/81575432/0c56a233-b0c3-4890-a68c-4f6e58c517ae">

Do you have an idea to more easily show there are many queries? I thought the count on the group row would be enough but may not 😆 

Thanks again for getting back to me and helping to improve things. 
If you have any ideas for changes, improvements or new features go ahead and raise an issue for them and I will take a look at get them in.

**Comment by mihailTr-19** [comment]
Hi!

Yep, I know that I can see the callstack, but I want to say, that before I shoudtn't clink on the query to see that details (full query, callstack). But of course it's up to you. And I know, that I'm really not good at UI/UX, so probably you are right. :)

So and another thing. If you've already had founded the SELECT, FROM, WHERE words (for the new functionality), probably it will nice if you mark them (bold, another color, etc).

As for me:
PS: We, programmers, are lazy people.
PSS: We could spend two hours for writing a code that will save 0.1 sec, that is needed for additional click on smth.
