### ISSUE TITLE
bug: export to csv

### ISSUE THREAD

**Issue by obaelde** [certinia/debug-log-analyzer#363]
### Summary

on the analysis tab, when clicking on the 3 dots in order to export to CSV, per documentation, nothing happens in visual studio

### Steps To Reproduce

1.  go to tab analysis
2. locate the 3 dots in header. for example near Type
3. export to csv button appears.
4. click on it
5. nothing happens. no windows opens to save to a folder. 
6. tried as well the CTRL C.   can copy but no delimiter between numbers columns (total time, self time). thus unuseable as the 2 columns are in paster together without space or delimiter.  thus can not paste in separate column in excel

### Expected result

in step 4 above: see the standard window to save file to a folder appearing

### Actual result

nothing happens. no windows open to save to a folder 

### Additional information

when using ctrlc-c.  no delimiter between columns for the numbers total time and self time
vlocity_cmt.AttributeValuesService(Map<String,ANY>,vlocity_cmt.AttributeMetadataService)CONSTRUCTOR_ENTRY84.4653.250
vlocity_cmt.TelcoOrderItemTriggerHandler()CONSTRUCTOR_ENTRY43.8013.172

can not paste it in excel as there is no way to define to a delimiter to place each log column in. a separate column in excel

**VS Code Version**:
Version: 1.81.0 (Universal)

**Log Analyzer Extension Version**:

1.7.1

**OS and version**:

macos ventura 13.5

**Comment by lcottercertinia** [comment]
Thanks for the report, it really helps get stuff sorted :) I will take a look next week.
I am hoping we can get this sorted pretty quick.

I have done a quick check though and everything seems to be working as expected for me.
I tested with vscode 1.81.0 (Universal) and 1.82.0-insider.

**Export to CSV**
Clicking `Export to CSV` shows me the save file dialog + saves the file
<img width="474" alt="image" src="https://github.com/certinia/debug-log-analyzer/assets/81575432/e4c4882b-193f-4ce6-b403-f503c91109be">

content looks like this
<img width="799" alt="image" src="https://github.com/certinia/debug-log-analyzer/assets/81575432/204266ed-49c6-463d-ad42-ec20cb1e59f0">

**Copy to clipboard**
I get spaces between columns
<img width="914" alt="image" src="https://github.com/certinia/debug-log-analyzer/assets/81575432/7620eecb-ee5f-4b2a-94e0-f7f87241bb0f">

and can paste into a spreadsheet
<img width="632" alt="image" src="https://github.com/certinia/debug-log-analyzer/assets/81575432/3d934537-2f11-48b6-9b1a-384c4bd2f9da">

Could you open developer tools in vscode and check the console to see if there are any errors in console?
Could you also open the output panel (CMD+SHIFT+u) then change the dropdown to lana and share any warnings / error there too?

**Comment by obaelde** [comment]
Hello

thank you for your email.

yes found the issue. apparently i need to open a folder in VSC . at that
point , when clicking on the export csv , i now see the window to select
save the file.
before i was simply opening VSC,  opening the log file .

not sure if it is the real reason but now at least i have the possibility
to save the export files.






*Olivier Baelde*


Senior Program Architect|Salesforce

Advisory Services - CSG

5 Temasek Boulevard, #13-01 Suntec Tower Five,

038985 Singapore

email: ***@***.***



<http://pages.mail.salesforce.com/Redirect.aspx?EQ=TgaVVQZ1J7qqi1NuwwmoGXBfnbSGEtKnrW372jdPuYbnkbv6Gub5QfDJZDzoAHgfXR_pslZMg-9-DQz1MioMPlkQR-20zmeulS4EnFgWF_2rVPf3uOojMdyB9BhNc4vwxxEmvcxcD759_0M4sK4zTmVMJWIQHYu2g1hDTQvKQagor6WfzivLTWdOxYueUxHxWCZZ_IwW27NIVx2-Q0pQjWiaNft_GHvYmnuRJ7MuSC_r52pVSSlxtQiSisjabzMwnjQtS4YTqZXBUe3e2yKmvX4EmlAMGlKudCFkCHGvdd86jVgWdWdHl5Vb5NmcFZP8eRm9drz3X21JQHw1>
---
Stay Connected
Event Calendar
<http://pages.mail.salesforce.com/Redirect.aspx?EQ=vfwtIJimFr6enhJEjYrIHSgeTmVeIcNFHaYCwfMfo9op6rrcdOQCMdqPqryEEk8vJNko6MqKw648oWVavwQi_82LbLvIeMkjfv__hcJgXJXtHYXrs9NIANAIDZHZgUwiZtaoByBzqfgFkBFqLpeshQ2x0LXTmSBN9Gg-iickF6IoJ0OxcnPvIQwaqscrRlNDMaZaFDojKjdkXvuB3C0Y0dFnzj1ZvVTkC7mfyGoWucO7ZGWWzGZRl4aAYv08kJ9yxvM9CDcuGbLfdsAjrcrC7N0OzQe3cIdYemg1CxY16YoGmgWE-HEh-g6Oq-K2j8rnb44Rx38SK8bB5Sg1>
  Success Hub
<http://pages.mail.salesforce.com/Redirect.aspx?EQ=Opi-YTu0DOdvCTIdC-j8nndNv3jlgXUcKlBNGBz8b0-UpHpzcTTjyuuW5WOpvnuOVnJbH6z5kPx1CIpqHV0BRUaSwseGcL1rDvEIinUG6yXjVukj7mBRvm9bc5ggU1MV5tIlSo2N99_98kY6X8WUA7d9Ma-NlD6MHegFVLw6UT_ND7MArMBPA9RNSN0nqCovr2ILrTBRSKk0nhaEg-_6DlamdlN-FsIngU282j_RxGn8fNDNafldgcT8_evpQHwqRG-hamJC7PrOyHSGsITgJQZ37W3tOMZHD8Dt_QX9NID0936YVrLv5EQu23mMYSyNb6rbBLTCnZdUrwk1>
  How are we doing?
<http://pages.mail.salesforce.com/Redirect.aspx?EQ=ew-lG9EkkcqIu7SqbBSsFt9IZbMT37JvdSXeT8r1ugpNvBDG_sdMRxGTSfQz1BUNX8oRpwnR1dxkFIye8gP2YwKUgrrrFOa9mvlRlCpC5YNFilSUH_btBnVmjCVr2bfvk--zeIul76TWKdTDOU_6HRhn9XBfTBIrV34JeP2MdhgS8V4rNVZHJulaaXfXgGa19ojI8kQukxD3dP34SgS6SPNDRDSIJJ39m__OMx8v5qwS9Mz1cDnNXiR-4gbBrjsTv-MErVs753njUqlMOBnkntXHm7my9FibCd_HKmIg7EJhOYgQTgi_8cuvZ3YO4kH4UIEWJ-UTmss5QbM1>

--


<https://smart.salesforce.com/sig/cgoh//us_mb/default/link.html>

**Comment by lcottercertinia** [comment]
@obaelde Perfect 🙏🏻  thank you for that. 
I have found the bug, we were making the assumption that a workspace (folder) would exist to use as a default. 
I can get a fix in for the next release and we can get this working when no workspace exists too.

I am glad you have a workaround though in the mean time 👍🏻
