### ISSUE TITLE
bug: export to csv unable to save file

### ISSUE THREAD

**Issue by nicolashamez-dev** [certinia/debug-log-analyzer#461]
### Summary

When analyzing a log, the export to csv function generates an error message after selecting the directory : Unable to save file: ENOENT: no such file or directory, open 'c:\C:\DEV\xxxx \analysis.csv'

### Steps To Reproduce

1.  Open log file
2. command "Log : Show Apex Log Analysis"
3. Navigate to Analysis tab
4. Use three points to export to CSV
5. Choose a directory

### Expected result

Tab data is export to csv format

### Actual result

VS Code toast error : Unable to save file: ENOENT: no such file or directory, open 'c:\C:\DEV\xxxx \analysis.csv'

### Additional information

**VS Code Version**: v1.84.2

**Log Analyzer Extension Version**: v 1.12.0

**OS and version**: Windows 10 Professionnal 64 bits

**Comment by lcottercertinia** [comment]
@nicolashamez-dev 
I have published[ v1.12.1](https://marketplace.visualstudio.com/items?itemName=financialforce.lana). 
It should fix the issue, but I did not have a windows machine to hand to test it. 

Can you give it a go and if it does not resolve the issue let me know and I will take another look.

**Comment by lcottercertinia** [comment]
I managed to test this is an Windows VM and it appears to be resolved. 
Let me know if you have a further issue 👍🏻

**Comment by nicolashamez-dev** [comment]
Sorry for the delay, I confirm that it works again

**Comment by lcottercertinia** [comment]
> Sorry for the delay, I confirm that it works again

@nicolashamez-dev 
I'm glad it's sorted 👍🏻
