### ISSUE TITLE
bug: Unable to download logs with 'Log: Retrieve Apex Log And Show Analysis'

### ISSUE THREAD

**Issue by judd1337** [certinia/debug-log-analyzer#490]
### Summary

I've installed the extension in Visual Studio Code and just followed the guide lines and did the command "Log: Retrieve Apex Log And Show Analysis" from Command Palette. It keeps throwing and error saying:

Command 'Log: Retrieve Apex Log And Show Analysis' resulted in an error
- Cannot read properties of undefined (reading 'ConfigAggregator')

### Steps To Reproduce

1.  Install the Apex Log Analyzer (v1.14.0) extension in Visual Studio Code
2.  Try to run 'Log: Retrieve Apex Log And Show Analysis' in Command Palette
3.  Error is thrown in a popup windows

### Expected result

I believe it should allow me to download logs files from my connected salesforce sandbox.

### Actual result

An error is thrown in a popup window:
Command 'Log: Retrieve Apex Log And Show Analysis' resulted in an error
- Cannot read properties of undefined (reading 'ConfigAggregator')

### Additional information

_Feel free to attach a screenshot_.
![Apex Log Analyzer error](https://github.com/certinia/debug-log-analyzer/assets/102535293/38b6ec25-1084-46e5-b6b0-103bf5819f51)

**VS Code Version**: 
Version: 1.86.2 (system setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0

**Log Analyzer Extension Version**:
v1.14.0

**OS and version**:
OS: Windows_NT x64 10.0.19045

**Comment by lcottercertinia** [comment]
@judd1337 Thanks for the report. I can reproduce and will get this sorted asap.

**Comment by lcottercertinia** [comment]
@judd1337 
This should be fixed and the update available
