### ISSUE TITLE
feat: Improve help documentation

### ISSUE THREAD

**Issue by kjonescertinia** [certinia/debug-log-analyzer#65]
### Is your feature request related to a problem?

Now the hep documentation has been moved to gh-pages we can provide better guidance on how to use the tool. Ideally we would include some screenshots to be better able to guide people.

**Comment by lcottercertinia** [comment]
I think we should also adopt a theme to aid navigation and search etc. 
This one seems to be pretty good https://github.com/just-the-docs/just-the-docs

**Comment by lcottercertinia** [comment]
#498 Migrates the doc site to docusaurus. 
We can now add content much for easily on a much better site going forward
