### ISSUE TITLE
feat: can we have a command to strip everything from a log except the debug statements 

### ISSUE THREAD

**Issue by nawforce** [certinia/debug-log-analyzer#86]
### Is your feature request related to a problem?

It's common when debugging to just want to look at the DEBUG lines. You can do this in DevConsole but I have to log into the org to do see that and keep the window open. It would be useful to just be able to download the log from the org and have everything but the debug stripped for me.

### Describe the solution you'd like

Ideally a command that both downloads and strips the log, so I only need to invoke one command. 

### Describe alternatives you've considered

A command that strips the log once I have downloaded it or a way to extract the DEBUG lines and display in output. These are OK but not as nice as the single command approach.

### Additional context

https://twitter.com/RobSalesforce/status/1485265134163484675, see also Jim request for similar

**Comment by PawelWozniak** [comment]
Nice idea I would like to see that as another internal tab. 
An additional feature could be that I can jump to full log from the exact line of this shortened log.
Another feature could be to show not only debugs but all exceptions.
<img width="336" alt="2022-09-16_09h59_23" src="https://user-images.githubusercontent.com/5740564/190587945-3650c6bc-970e-40a8-9e41-16f965dc5dff.png">

**Comment by lcottercertinia** [comment]
I have been giving this some thought and I think we can do a number of things for this.

1. Enable filtered by event type on the call tee - This will keep the context of the call stack but remove all other events.
2. Code lense to show only debugs - code lense on the log file to collapse all other lines except debug.
3. Timeline filtering / search - search on timeline to highlight the debug event. Then show the content  in the over over.

**Comment by lcottercertinia** [comment]
There is now a PR which add Debug Only filtering to the Call Tree. 
I have also  experimented with a code lens which folds the code to show only the debug statements but this is not really what this feature is for. VsCode lack filtering on the editors too.

Point 3 we can do when we get to search on timeline
